<a href="https://colab.research.google.com/github/mib-a/AI-ML-Learning/blob/main/mib-a/AI-ML-Learning/Month-03-Deep-Learning/Module-11/Breast_Cancer_Python_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 11.3 Data Loading and Basic Preprocessing

## Import Libraries

In [134]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [135]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

Little About the Neural Architecture:

input = 30, neuron = 1, ACT = Sigmoid, Output = y_pred

In [136]:
df.shape

(569, 33)

### Dropping Unnecessary Cols (reducing Dimensionality)

In [137]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [138]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

## Train Test Split

In [139]:
# X = df.drop(columns=['diagnosis'])
# y = df['diagnosis']
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2, random_state = 42)

## Preprocessing

### Scaling (neural models perform better when the data are scaled)

In [140]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [141]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

### Label Encoding (Encoding the M/B target dataset)

In [142]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [143]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0])

### Numpy arrays to PyTorch tensors (To use PyTorch Training Pipelines)

In [144]:
type(X_train)

numpy.ndarray

So that's a numpy array, all the variables here are numpy arrays. But to use PyTorch Training Pipeline they need to be transferred into PyTorch Tensors.

In [145]:
# transformed_tensor_var = torch.tensor(numpy_array_name)

X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [146]:
type(X_train_tensor)

torch.Tensor

In [147]:
X_train_tensor.shape # (row, col)

torch.Size([455, 30])

In [148]:
y_train_tensor.shape # (row) as col 1 only

torch.Size([455])

## Defining the Model

In [149]:
X_train_tensor.shape

torch.Size([455, 30])

In [150]:
class MySimpleNN():

  def __init__(self, X): # constructor (self(to call w & b), input)
    # initializing weight (size: (30*1)) (to match the matmul operation without Transpose matrix)
    self.weights = torch.rand(X.shape[1], # num of rows = no of input/cols (num of col in input dataset)
                              1, # num of col = 1 # as all features going to only one neuron
                              dtype=torch.float64, # must be float, gradient of int type can't be calculated
                              requires_grad=True)  # keeps track

    # initializing bias (1*1)
    self.bias = torch.zeros(1, # 1 element matrix for the only one neuron
                            dtype=torch.float64,
                            requires_grad=True)

  def forward(self, X): # (self, input); Z = WX + b
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):

    # Clamp predictions to avoid log(0) or log(1) respective to undefined or 0.
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon) # var = torch.clamp(var, min, max)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

You can check the weights and biases after training the pipeline

### Important Parameters (lr and epoch)

In [151]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [152]:
# create model
model = MySimpleNN(X_train_tensor) # training the model on train dataset

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update: so it renew every time ~ = the loop doesnt change the values each time of w_old.
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}') # epoch + 1 as count starts from zero

Epoch: 1, Loss: 3.0361871941075496
Epoch: 2, Loss: 2.898873636105541
Epoch: 3, Loss: 2.7542220679039713
Epoch: 4, Loss: 2.6053572228172994
Epoch: 5, Loss: 2.455029701115578
Epoch: 6, Loss: 2.3034081063657603
Epoch: 7, Loss: 2.15336268167628
Epoch: 8, Loss: 2.005772376312471
Epoch: 9, Loss: 1.8584535106092612
Epoch: 10, Loss: 1.71683735974833
Epoch: 11, Loss: 1.583454320269862
Epoch: 12, Loss: 1.4620997979773669
Epoch: 13, Loss: 1.3538509186458472
Epoch: 14, Loss: 1.259383356414871
Epoch: 15, Loss: 1.178867110259505
Epoch: 16, Loss: 1.1119527213348397
Epoch: 17, Loss: 1.057757505918084
Epoch: 18, Loss: 1.0148318528480593
Epoch: 19, Loss: 0.9812247336655828
Epoch: 20, Loss: 0.9547637868480685
Epoch: 21, Loss: 0.9334451049309215
Epoch: 22, Loss: 0.9156920545725192
Epoch: 23, Loss: 0.900396315755285
Epoch: 24, Loss: 0.8868288818564756
Epoch: 25, Loss: 0.8745250458539205

In [153]:
model.weights
model.bias

tensor([-0.1947], dtype=torch.float64, requires_grad=True)

## Evaluation

In [154]:
y_pred # only printing the 30th element to avoid the whole list.

tensor([[0.2171],
        [0.6024],
        [0.9346],
        [0.8570],
        [0.9517],
        [0.7397],
        [0.8820],
        [0.1676],
        [0.4838],
        [0.2356],
        [0.7303],
        [0.2816],
        [0.2352],
        [0.6888],
        [0.2104],
        [0.4945],
        [0.2071],
        [0.6895],
        [0.3095],
        [0.7832],
        [0.0412],
        [0.3808],
        [0.2312],
        [0.9163],
        [0.2287],
        [0.5052],
        [0.4681],
        [0.4200],
        [0.1365],
        [0.0897],
        [0.4282],
        [0.6789],
        [0.4791],
        [0.6672],
        [0.4069],
        [0.0967],
        [0.4013],
        [0.3366],
        [0.3822],
        [0.4051],
        [0.6636],
        [0.1835],
        [0.6098],
        [0.8110],
        [0.1811],
        [0.3365],
        [0.9927],
        [0.2059],
        [0.4622],
        [0.2904],
        [0.9614],
        [0.3223],
        [0.2377],
        [0.8304],
        [0.8958],
        [0.8585],
        [0.0273],
        [0.2023],
        [0.1014],
        [0.2768],
        [0.3367],
        [0.6560],
        [0.6478],
        [0.1230],
        [0.3649],
        [0.1852],
        [0.5153],
        [0.5195],
        [0.1299],
        [0.5079],
        [0.2923],
        [0.6484],
        [0.6413],
        [0.1898],
        [0.0630],
        [0.8023],
        [0.6391],
        [0.2242],
        [0.4909],
        [0.6912],
        [0.9295],
        [0.3456],
        [0.6288],
        [0.3049],
        [0.6074],
        [0.1769],
        [0.3033],
        [0.4626],
        [0.9628],
        [0.3486],
        [0.5005],
        [0.7021],
        [0.2172],
        [0.5985],
        [0.4190],
        [0.5867],
        [0.3334],
        [0.8818],
        [0.5959],
        [0.7270],
        [0.7809],
        [0.6227],
        [0.2865],
        [0.5635],
        [0.3208],
        [0.8284],
        [0.6478],
        [0.4964],
        [0.5849],
        [0.5024],
        [0.6023],
        [0.8218],
        [0.3641],
        [0.6868],
        [0.3519],
        [0.6521],
        [0.4276],
        [0.0826],
        [0.9954],
        [0.2705],
        [0.4837],
        [0.0852],
        [0.4360],
        [0.2366],
        [0.1713],
        [0.7582],
        [0.3600],
        [0.4164],
        [0.4787],
        [0.3782],
        [0.2610],
        [0.0370],
        [0.1584],
        [0.0711],
        [0.3884],
        [0.2557],
        [0.2567],
        [0.5301],
        [0.0931],
        [0.6100],
        [0.1391],
        [0.9716],
        [0.4386],
        [0.6613],
        [0.2523],
        [0.5461],
        [0.5821],
        [0.3413],
        [0.8038],
        [0.6907],
        [0.3782],
        [0.7689],
        [0.3395],
        [0.5570],
        [0.1325],
        [0.1942],
        [0.1738],
        [0.2738],
        [0.5412],
        [0.2369],
        [0.3880],
        [0.3322],
        [0.8428],
        [0.8812],
        [0.1679],
        [0.7632],
        [0.1602],
        [0.6914],
        [0.2587],
        [0.5865],
        [0.2533],
        [0.2675],
        [0.3289],
        [0.9846],
        [0.1935],
        [0.3051],
        [0.5857],
        [0.7532],
        [0.1744],
        [0.7792],
        [0.3366],
        [0.9491],
        [0.6806],
        [0.4597],
        [0.0834],
        [0.2386],
        [0.2244],
        [0.1420],
        [0.4865],
        [0.3533],
        [0.3405],
        [0.7968],
        [0.1550],
        [0.5756],
        [0.8462],
        [0.5745],
        [0.3116],
        [0.5652],
        [0.5416],
        [0.6556],
        [0.5241],
        [0.6596],
        [0.9790],
        [0.3367],
        [0.9052],
        [0.7117],
        [0.1733],
        [0.1532],
        [0.5185],
        [0.6606],
        [0.3357],
        [0.7833],
        [0.3200],
        [0.6656],
        [0.1837],
        [0.7811],
        [0.4229],
        [0.2177],
        [0.3807],
        [0.1134],
        [0.3793],
        [0.8620],
        [0.5203],
        [0.3311],
        [0.3825],
        [0.7593],
        [0.5216],
        [0.5267],
        [0.6063],
        [0.2729],
        [0.1195],
        [0.5786],
        [0.2921],
        [0.5540],
        [0.8616],
        [0.3844],
        [0.2188],
        [0.3714],
        [0.3897],
        [0.2189],
        [0.6391],
        [0.7095],
        [0.5813],
        [0.1019],
        [0.8083],
        [0.2700],
        [0.1118],
        [0.2236],
        [0.1357],
        [0.8404],
        [0.9622],
        [0.4134],
        [0.9938],
        [0.8259],
        [0.8744],
        [0.6082],
        [0.3014],
        [0.3282],
        [0.8138],
        [0.2023],
        [0.5052],
        [0.4315],
        [0.4105],
        [0.5067],
        [0.9621],
        [0.2605],
        [0.0579],
        [0.2098],
        [0.2259],
        [0.2547],
        [0.7826],
        [0.4092],
        [0.2612],
        [0.6274],
        [0.6841],
        [0.6682],
        [0.2353],
        [0.2567],
        [0.2748],
        [0.8959],
        [0.0565],
        [0.1911],
        [0.5095],
        [0.2728],
        [0.2957],
        [0.5142],
        [0.1200],
        [0.8461],
        [0.5225],
        [0.2197],
        [0.1156],
        [0.2035],
        [0.9976],
        [0.7133],
        [0.4558],
        [0.1489],
        [0.6886],
        [0.3832],
        [0.8135],
        [0.2984],
        [0.1060],
        [0.3656],
        [0.8751],
        [0.2715],
        [0.1597],
        [0.2206],
        [0.7243],
        [0.6063],
        [0.5619],
        [0.2400],
        [0.3288],
        [0.1427],
        [0.5517],
        [0.4685],
        [0.4127],
        [0.3480],
        [0.3877],
        [0.1857],
        [0.3784],
        [0.2438],
        [0.0840],
        [0.6633],
        [0.1962],
        [0.0537],
        [0.5265],
        [0.2562],
        [0.3135],
        [0.2999],
        [0.4065],
        [0.4601],
        [0.0994],
        [0.4670],
        [0.4877],
        [0.7679],
        [0.1717],
        [0.4050],
        [0.4003],
        [0.6232],
        [0.7288],
        [0.2809],
        [0.4985],
        [0.5266],
        [0.5857],
        [0.3118],
        [0.0908],
        [0.6325],
        [0.2917],
        [0.7842],
        [0.2444],
        [0.3469],
        [0.6395],
        [0.2656],
        [0.8119],
        [0.1241],
        [0.6229],
        [0.1887],
        [0.7658],
        [0.3940],
        [0.1482],
        [0.2612],
        [0.4897],
        [0.3621],
        [0.3760],
        [0.1721],
        [0.4936],
        [0.1646],
        [0.2010],
        [0.6232],
        [0.6694],
        [0.8034],
        [0.2965],
        [0.4224],
        [0.5087],
        [0.8941],
        [0.6968],
        [0.6541],
        [0.1309],
        [0.2775],
        [0.7649],
        [0.3929],
        [0.7810],
        [0.2728],
        [0.8849],
        [0.4512],
        [0.4120],
        [0.4145],
        [0.4993],
        [0.2482],
        [0.6766],
        [0.1975],
        [0.3037],
        [0.4606],
        [0.7571],
        [0.0960],
        [0.9471],
        [0.3076],
        [0.1859],
        [0.7572],
        [0.1462],
        [0.9330],
        [0.6100],
        [0.1106],
        [0.7767],
        [0.1844],
        [0.4718],
        [0.1290],
        [0.7374],
        [0.3240],
        [0.9196],
        [0.2894],
        [0.4023],
        [0.7749],
        [0.2700],
        [0.6313],
        [0.1222],
        [0.2699],
        [0.5192],
        [0.0227],
        [0.3305],
        [0.0212],
        [0.5869],
        [0.4322],
        [0.6397],
        [0.1505],
        [0.1014],
        [0.2257],
        [0.6291],
        [0.1071],
        [0.1854],
        [0.2002],
        [0.1638],
        [0.7529],
        [0.8138],
        [0.4517],
        [0.9080],
        [0.5452],
        [0.7689],
        [0.1253],
        [0.9588],
        [0.1611],
        [0.4342],
        [0.5809],
        [0.2557],
        [0.7221],
        [0.5166],
        [0.1050],
        [0.9829],
        [0.1105],
        [0.6115],
        [0.2355],
        [0.3603],
        [0.4357],
        [0.3090],
        [0.2871],
        [0.6619]], dtype=torch.float64, grad_fn=<SigmoidBackward0>)

Notice how y_pred is also tracking. We've already seen this in the computational graph. After sigmoid operation we get y_pred. So y_pred is also in requires_grad.

In [155]:
# model evaluation
with torch.no_grad(): # y_pred is also tracking so it will change the value with each loop; that's why the whole thing needs to be under no_grad()
  y_pred = model.forward(X_test_tensor) # getting the y_pred tensor
  y_pred = (y_pred > 0.9).float() # y_pred True if greater than 0.9. Then applying float to convert it to 0/1 (as accuracy range is 0 to 1)
  # accuracy = all true assumptions/ all assumptions
  accuracy = (y_pred == y_test_tensor).float().mean() # accuracy = if y_pred = y (T/F); then converting to float. Then the mean of all the 1 + 0! (! Dividing by all assumptions means mean)
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6077254414558411

In [156]:
accuracy

tensor(0.6077)

Only writing accuracy will give u a result like this. To access the values from the tensor, we use item. Like
`
accuracy.item()
`

In [157]:
y_pred # y_pred = (y_pred > 0.9 ).float()

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.]])