<a href="https://colab.research.google.com/github/mib-a/AI-ML-Learning/blob/main/mib-a/AI-ML-Learning/Month-03-Deep-Learning/Module-15/15_Breast_Cancer_DataSet_and_DataLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [248]:
import numpy as np # numpy array
import pandas as pd # to handle the csv file
import torch # dataset and dataloader also everything is in tensor
# preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

# WorkFlow
```
RAW CSV
   ↓
Pandas DataFrame
   ↓
Remove useless columns
   ↓
Separate X and y
   ↓
Train/Test Split
   ↓
StandardScaler
   ↓
LabelEncoder
   ↓
NumPy arrays
   ↓
PyTorch tensors
   ↓
CustomDataset
   ↓
DataLoader
   ↓
Batches
   ↓
Neural Network
   ↓
Forward Pass
   ↓
Prediction
   ↓
Loss
   ↓
zero_grad()
   ↓
backward()
   ↓
optimizer.step()
   ↓
Repeat for epochs
   ↓
Test/Evaluation
   ↓
Accuracy

## 15.2 DataSet & DataLoader
  Why Necessary? Problems with our previous Code:
  - Batch can't be created
  - memory inefficient
  - takes so much time to converge

## Dataset Uploading & Preprocessing

In [249]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [250]:
df.shape

(569, 33)

#### Dropping Unnecessary Cols (reducing Dimensionality)

In [251]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [252]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

#### Train test split

In [253]:
print(df.iloc[:, 1:].shape) # all features (X)
print(df.iloc[:, 0].shape) # labels (y)

(569, 30)
(569,)

In [254]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:],
                                                    df.iloc[:, 0],
                                                    test_size=0.2)

#### Scaling features (neural networks perform better on scaled data)

- x_scaled = (x - mean) / standard_deviation

In [255]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
# fit: learning the mean and std from X-train
# Use those to transform y_train

X_test = scaler.transform(X_test)
# transforms using X-train's statistics
# if u fit_transform, model will be able to see all ur test samples and memorize, overfit: Data leakage

In [256]:
print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_train: {type(X_train)}\n")

print(X_train)

Shape of X_train: (455, 30)
Shape of X_train: <class 'numpy.ndarray'>

[[-2.04171767 -1.40180979 -1.9982406  ... -1.7630841   0.03866535
   0.53579434]
 [ 1.511206    0.94227358  1.54400657 ...  0.63709008  0.01940499
  -0.44698233]
 [ 0.33824625  1.35429221  0.4353675  ...  1.34302367  1.7961732
   0.81039371]
 ...
 [-0.11663326  0.32075396 -0.07120167 ...  0.62481298  0.46239327
   1.71868392]
 [-0.78607857 -0.13083708 -0.81984446 ... -0.81114801  0.5763504
  -0.79162121]
 [-0.15096379 -0.37525491 -0.23562904 ... -0.96737418 -0.91953756
  -1.19796157]]

#### Label Encoding

In [257]:
print(df['diagnosis'].unique())
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

['M' 'B']

In [258]:
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_train: {type(y_train)}\n")

print(y_train)

Shape of y_train: (455,)
Shape of y_train: <class 'numpy.ndarray'>

[0 1 1 1 1 1 1 1 0 1 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 1 1 0 0 0 1
 1 1 0 1 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1
 1 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1 1 0 0 0
 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 0 1 0 1 1 0 0 0 0 1 0 0
 0 1 1 1 0 0 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0 1 0
 1 0 1 0 0 0 0 0 1 1 0 1 0 1 1 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 1 1
 0 1 0 1 0 1 0 1 0 1 1 1 1 0 1 0 1 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 1
 0 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 0 0 1 0
 0 1 0 0 1 0 0 0 0 1 1 1 0 1 0 1 1 0 0 1 0 0 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0
 1 1 1 0 1 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0
 0 0 1 0 0 0 0 0 1 0 0]

Note: Now the df is still unchanged, the arrays have been changed only.

### Numpy Array to tensors

In [259]:
# tensor = torch.tensor (nd_array_name, dtype = torch.float32)

# 1. nd_array -> tensor ; 2. tensor dtyep to float
X_train_tensor = torch.tensor(X_train, dtype = torch.float32)
X_test_tensor = torch.tensor(X_test, dtype = torch.float32)
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

# less redundant way
y_train_tensor = torch.tensor(y_train, dtype = torch.float32)
y_test_tensor = torch.tensor(y_test, dtype = torch.float32)

/tmp/ipykernel_3377/1977528520.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_3377/1977528520.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

In [260]:
type(X_train_tensor) # chekcing types after conversion

torch.Tensor

# Dataset and Dataloader
- Dataset
  - creates the dataset
  - parameters: X, y (features, labels)
- DataLoader
  - feeds the dataset to the model

In [261]:
from torch.utils.data import Dataset,DataLoader

## Custom Dataset Class Creation
It is to make some useful functions which we can use for the rest of our code to call and use the dataset easily.

In [262]:
class CustomDataset(Dataset): # class creation
  def __init__( self,features,labels): # constructor
    self.features = features # Takin the features that were given to me (self.) and store them inside this Dataset object under the name self.features
    self.labels = labels

  def __len__(self): # len(Dataset) will give u the len quickly ~= num of rows
    return self.features.shape[0]

  def __getitem__(self,index): # gives sample acc to index number
    return self.features[index], self.labels[index]

## Making the train & test dataset

In [263]:
"""
new_dataset = CustomDataset( # calling the class
  X # feature tensor (must be tensor as the class is being called from torch)
  y # the label tensor
  )
"""

train_dataset = CustomDataset(X_train_tensor,y_train_tensor) # train_dataset = CustomDataset (features, labels)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

## Using other functions of CustomDataset Class

### __len__ function

In [264]:
len(train_dataset)

455

### __getitem()__ function
- returns (feature_vector, label)

In [265]:
train_dataset[2] # for the third sample

(tensor([ 0.3382,  1.3543,  0.4354,  0.2292,  0.8641,  1.2343,  0.9904,  1.0060,
          0.4186,  0.3598,  0.1561, -0.3999,  0.3702,  0.1037, -0.6026,  0.2563,
          0.1054, -0.1624, -0.3486, -0.3185,  0.8286,  1.7542,  1.2547,  0.6835,
          1.3760,  2.2445,  1.6765,  1.3430,  1.7962,  0.8104]),
 tensor(1.))

# DataLoader

In [266]:
train_loader = DataLoader(train_dataset,
                          batch_size=32,
                          shuffle=True)
test_loader = DataLoader(test_dataset,
                         batch_size=32,
                         shuffle=True) # doesnt need to be shuffled tho

# Defining the Model
1. 30 features goes to one neuron
2. Assign weights for each feature
3. Linear Transformation, Z = WX + b
4. Sigmoid, ouput = Sigmoid(Z)

In [267]:
import torch.nn as nn

In [268]:
# num of input features
X_train_tensor.shape[1]

30

In [269]:
class MySimpleNN (nn.Module): # inheriting nn module in this class, requires train_features
  def __init__(self, num_features): # constructor # receives num of input features
    super().__init__() # nn.Module Class initialization # lets python tracks model's params

    self.linear = nn.Linear (num_features, 1)
    # nn.Linear Transformation Operation (input nodes, output nodes) # 30 inputs and 1 direct output
    self.sigmoid = nn.Sigmoid () # the ACT was Sigmoid, so bringing that

  def forward (self, features):
    output = self.linear(features) # Linear Transformation Output
    # print(f"Linear Transformation Output: {output}")
    output = self.sigmoid(output) # it will save memory as being saved on the same storage
    # print(f"\nActivation Function Ouput: {output}")

  # do not need to write loss function def here, as nn has it's own BCELoss Function

    return output

In [270]:
learning_rate = 0.1
epochs = 25

## Parameters (need to feed the model X_train dataset to see the parameters)

In [271]:
loss_function = nn.BCELoss()

In [272]:
type(loss_function)

torch.nn.modules.loss.BCELoss

## Model : Creating the Neural Network Model

In [273]:
model = MySimpleNN(X_train_tensor.shape[1])

In [274]:
model.parameters()

In [275]:
X_test_tensor.dtype

torch.float32

In [276]:
model.linear.weight.dtype

torch.float32

In [277]:
y_train_tensor.dtype

torch.float32

In [278]:
model.parameters()

# Training PipeLine

### Training Pipeline (with build DataLoader)

In [279]:
#create model
model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD (model.parameters(),
                            lr = learning_rate )

#define loop
for epoch in range(epochs):

  for batch_feature,batch_labels in train_loader:
    #forward pass
    y_pred = model(batch_feature)
    #Loss calculate
    loss = loss_function(y_pred,batch_labels.reshape(-1,1))

    # clear old gradient
    optimizer.zero_grad()
    # calculate new gradients
    loss.backward()
    # update weights and bias
    optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.16167764365673065
 2 , Loss = 0.16927912831306458
 3 , Loss = 0.14045539498329163
 4 , Loss = 0.29048940539360046
 5 , Loss = 0.055535394698381424
 6 , Loss = 0.057029616087675095
 7 , Loss = 0.018780460581183434
 8 , Loss = 0.04692143201828003
 9 , Loss = 0.2827850878238678
 10 , Loss = 0.37273070216178894
 11 , Loss = 0.0066850618459284306
 12 , Loss = 0.010610370896756649
 13 , Loss = 0.01960355043411255
 14 , Loss = 0.06656012684106827
 15 , Loss = 0.03367467597126961
 16 , Loss = 0.035734303295612335
 17 , Loss = 0.08153467625379562
 18 , Loss = 0.04203344136476517
 19 , Loss = 0.3104443848133087
 20 , Loss = 0.008288740180432796
 21 , Loss = 0.04945632815361023
 22 , Loss = 0.10764051228761673
 23 , Loss = 0.1421002447605133
 24 , Loss = 0.28061145544052124
 25 , Loss = 0.008714504539966583

Note: Small technical note: this prints the loss from the last batch of each epoch, not the average loss over the whole epoch.

### Training pipeline with handmade dataloader

In [280]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop
batch_size = 32
epochs = 25
n_sample = len(X_train_tensor)

for epoch in range(epochs): # repeat wtv underneath for 25 times

  # creating batches manually (unnecessary)
  # range(start, end, step) = (0, n_sample, batch_size) = start at 0, move forward by 32, do it till u reach the num of samples
  for start_indx in range(0,n_sample,batch_size):
    end_indx = start_indx + batch_size # calcualting current batch end

    # print(f" Start index {start_indx}, end indx {end_indx}\n")

    X_batch = X_train_tensor[start_indx:end_indx] # features
    y_batch = y_train_tensor[start_indx:end_indx] # labels

    #forward pass
    y_pred = model(X_batch) # y_pred = model(X_train)
    loss = loss_function(y_pred,y_batch.reshape(-1,1)) # (-1,1) as y_pred (x,) & y_batch(x, 1)


    #upate step

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.20863084495067596
 2 , Loss = 0.1571677178144455
 3 , Loss = 0.1316423863172531
 4 , Loss = 0.11531227827072144
 5 , Loss = 0.10366841405630112
 6 , Loss = 0.09482705593109131
 7 , Loss = 0.08782730251550674
 8 , Loss = 0.08211668580770493
 9 , Loss = 0.07735062390565872
 10 , Loss = 0.07330102473497391
 11 , Loss = 0.06981004774570465
 12 , Loss = 0.06676429510116577
 13 , Loss = 0.06408007442951202
 14 , Loss = 0.06169398874044418
 15 , Loss = 0.059557028114795685
 16 , Loss = 0.057630717754364014
 17 , Loss = 0.055884264409542084
 18 , Loss = 0.05429280176758766
 19 , Loss = 0.05283588543534279
 20 , Loss = 0.0514967255294323
 21 , Loss = 0.050261158496141434
 22 , Loss = 0.04911736026406288
 23 , Loss = 0.04805520549416542
 24 , Loss = 0.0470661036670208
 25 , Loss = 0.0461425855755806

# Model Evaluation
- Ancient, not so good version
- Better Version

### Ancient Version

In [281]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.5627885460853577

### Better version

In [282]:
y_pred.shape

torch.Size([114, 1])

In [283]:
batch_labels.shape

torch.Size([7])

In [284]:
model.eval()  #evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item() # view(-1) automatically does the shape calculation and reshaping for u

    accuracy_list.append(batch_accuracy)


overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(overall_accuracy)

0.9765625

In [285]:
accuracy_list

[0.96875, 0.96875, 0.96875, 1.0]

# Summary

In [286]:
X_train_tensor.shape

torch.Size([455, 30])

In [287]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.13/dist-packages (1.8.0)

In [288]:
from torchinfo import summary

In [289]:
summary(model, input_size = (455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================

# Core Training Loop
```
for batch_features, batch_labels in train_loader:
    # Get one batch from the DataLoader

    y_pred = model(batch_features)
    # Forward pass: model makes predictions

    loss = loss_function(
        y_pred,
        batch_labels.reshape(-1, 1)
    )
    # Measure how wrong those predictions are

    optimizer.zero_grad()
    # Clear old gradients

    loss.backward()
    # Backpropagation: calculate new gradients

    optimizer.step()
    # Update weights using those gradients